///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ATS_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ATS_DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("71e66ae2-c24c-416c-8364-cdf3ea829333")]
    public partial class ATS_DemoRepository : RepoGenBaseFolder
    {
        static ATS_DemoRepository instance = new ATS_DemoRepository();
        ATS_DemoRepositoryFolders.FormVipApplicationAppFolder _formvipapplication;
        ATS_DemoRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the ATS_DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("71e66ae2-c24c-416c-8364-cdf3ea829333")]
        public static ATS_DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ATS_DemoRepository() 
            : base("ATS_DemoRepository", "/", null, 0, false, "71e66ae2-c24c-416c-8364-cdf3ea829333", ".\\RepositoryImages\\ATS_DemoRepository71e66ae2.rximgres")
        {
            _formvipapplication = new ATS_DemoRepositoryFolders.FormVipApplicationAppFolder(this);
            _explorer = new ATS_DemoRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("71e66ae2-c24c-416c-8364-cdf3ea829333")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormVipApplication folder.
        /// </summary>
        [RepositoryFolder("a31a518b-97fd-487a-a250-ba7838adc2b6")]
        public virtual ATS_DemoRepositoryFolders.FormVipApplicationAppFolder FormVipApplication
        {
            get { return _formvipapplication; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("056b4b23-8e8a-4d95-9307-55a2ac0ab589")]
        public virtual ATS_DemoRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ATS_DemoRepositoryFolders
    {
        /// <summary>
        /// The FormVipApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("a31a518b-97fd-487a-a250-ba7838adc2b6")]
        public partial class FormVipApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _rbmaleInfo;
            RepoItemInfo _btaddInfo;
            RepoItemInfo _vipcount1Info;
            RepoItemInfo _btclearInfo;
            RepoItemInfo _vipcount0Info;

            /// <summary>
            /// Creates a new FormVipApplication  folder.
            /// </summary>
            public FormVipApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormVipApplication", "/form[@controlname='formVipApplication']", parentFolder, 30000, null, true, "a31a518b-97fd-487a-a250-ba7838adc2b6", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First Name:']", 60000, null, "cb0a526b-7b1a-4071-9889-7b48666818d0");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last Name:']", 60000, null, "947bc6ae-871d-4cce-b7a2-d452d595dbe6");
                _musicInfo = new RepoItemInfo(this, "Music", ".//listitem[@accessiblename='Music']", 60000, null, "0b855724-6f2f-48e3-81a2-400b2d6af528");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//listitem[@accessiblename='Movie']", 60000, null, "05d8f0e2-3e99-4ab5-a85d-7abfe8c448c0");
                _rbmaleInfo = new RepoItemInfo(this, "RbMale", "?/?/radiobutton[@controlname='rbMale']", 60000, null, "aecd184b-31b9-4013-b0c3-c96e772c33a4");
                _btaddInfo = new RepoItemInfo(this, "BtAdd", "button[@controlname='btAdd']", 60000, null, "a3ee9e73-938d-4ed0-91bd-6e7e287cff26");
                _vipcount1Info = new RepoItemInfo(this, "VIPCount1", "?/?/text[@accessiblename='VIP count: 1']", 60000, null, "cfbc334c-9705-4acd-b4d4-399745e1ad44");
                _btclearInfo = new RepoItemInfo(this, "BtClear", "button[@controlname='btClear']", 60000, null, "0c93682a-2000-4c8f-8646-e3b6eb8af78c");
                _vipcount0Info = new RepoItemInfo(this, "VIPCount0", "?/?/text[@accessiblename='VIP count: 0']", 60000, null, "0147e638-ad6d-4877-940d-88f91441c6ed");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a31a518b-97fd-487a-a250-ba7838adc2b6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a31a518b-97fd-487a-a250-ba7838adc2b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("cb0a526b-7b1a-4071-9889-7b48666818d0")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("cb0a526b-7b1a-4071-9889-7b48666818d0")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("947bc6ae-871d-4cce-b7a2-d452d595dbe6")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("947bc6ae-871d-4cce-b7a2-d452d595dbe6")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("0b855724-6f2f-48e3-81a2-400b2d6af528")]
            public virtual Ranorex.ListItem Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("0b855724-6f2f-48e3-81a2-400b2d6af528")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("05d8f0e2-3e99-4ab5-a85d-7abfe8c448c0")]
            public virtual Ranorex.ListItem Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("05d8f0e2-3e99-4ab5-a85d-7abfe8c448c0")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The RbMale item.
            /// </summary>
            [RepositoryItem("aecd184b-31b9-4013-b0c3-c96e772c33a4")]
            public virtual Ranorex.RadioButton RbMale
            {
                get
                {
                    return _rbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RbMale item info.
            /// </summary>
            [RepositoryItemInfo("aecd184b-31b9-4013-b0c3-c96e772c33a4")]
            public virtual RepoItemInfo RbMaleInfo
            {
                get
                {
                    return _rbmaleInfo;
                }
            }

            /// <summary>
            /// The BtAdd item.
            /// </summary>
            [RepositoryItem("a3ee9e73-938d-4ed0-91bd-6e7e287cff26")]
            public virtual Ranorex.Button BtAdd
            {
                get
                {
                    return _btaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtAdd item info.
            /// </summary>
            [RepositoryItemInfo("a3ee9e73-938d-4ed0-91bd-6e7e287cff26")]
            public virtual RepoItemInfo BtAddInfo
            {
                get
                {
                    return _btaddInfo;
                }
            }

            /// <summary>
            /// The VIPCount1 item.
            /// </summary>
            [RepositoryItem("cfbc334c-9705-4acd-b4d4-399745e1ad44")]
            public virtual Ranorex.Text VIPCount1
            {
                get
                {
                    return _vipcount1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VIPCount1 item info.
            /// </summary>
            [RepositoryItemInfo("cfbc334c-9705-4acd-b4d4-399745e1ad44")]
            public virtual RepoItemInfo VIPCount1Info
            {
                get
                {
                    return _vipcount1Info;
                }
            }

            /// <summary>
            /// The BtClear item.
            /// </summary>
            [RepositoryItem("0c93682a-2000-4c8f-8646-e3b6eb8af78c")]
            public virtual Ranorex.Button BtClear
            {
                get
                {
                    return _btclearInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtClear item info.
            /// </summary>
            [RepositoryItemInfo("0c93682a-2000-4c8f-8646-e3b6eb8af78c")]
            public virtual RepoItemInfo BtClearInfo
            {
                get
                {
                    return _btclearInfo;
                }
            }

            /// <summary>
            /// The VIPCount0 item.
            /// </summary>
            [RepositoryItem("0147e638-ad6d-4877-940d-88f91441c6ed")]
            public virtual Ranorex.Text VIPCount0
            {
                get
                {
                    return _vipcount0Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VIPCount0 item info.
            /// </summary>
            [RepositoryItemInfo("0147e638-ad6d-4877-940d-88f91441c6ed")]
            public virtual RepoItemInfo VIPCount0Info
            {
                get
                {
                    return _vipcount0Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("056b4b23-8e8a-4d95-9307-55a2ac0ab589")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "056b4b23-8e8a-4d95-9307-55a2ac0ab589", "")
            {
                _startInfo = new RepoItemInfo(this, "Start", "?/?/button", 60000, null, "de30578a-5ea8-4be0-97eb-dc9df65801ff");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("056b4b23-8e8a-4d95-9307-55a2ac0ab589")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("056b4b23-8e8a-4d95-9307-55a2ac0ab589")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Start item.
            /// </summary>
            [RepositoryItem("de30578a-5ea8-4be0-97eb-dc9df65801ff")]
            public virtual Ranorex.Button Start
            {
                get
                {
                    return _startInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Start item info.
            /// </summary>
            [RepositoryItemInfo("de30578a-5ea8-4be0-97eb-dc9df65801ff")]
            public virtual RepoItemInfo StartInfo
            {
                get
                {
                    return _startInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
